// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.3
// source: cc.proto

package services

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ControlCenter_CreateCluster_FullMethodName     = "/proto.ControlCenter/CreateCluster"
	ControlCenter_GetFleet_FullMethodName          = "/proto.ControlCenter/GetFleet"
	ControlCenter_GetPoolStats_FullMethodName      = "/proto.ControlCenter/GetPoolStats"
	ControlCenter_CreatePingJob_FullMethodName     = "/proto.ControlCenter/CreatePingJob"
	ControlCenter_EvaluateJobs_FullMethodName      = "/proto.ControlCenter/EvaluateJobs"
	ControlCenter_GetJobs_FullMethodName           = "/proto.ControlCenter/GetJobs"
	ControlCenter_GetJobSummaryByID_FullMethodName = "/proto.ControlCenter/GetJobSummaryByID"
	ControlCenter_GetNewUUID_FullMethodName        = "/proto.ControlCenter/GetNewUUID"
	ControlCenter_GetPingResults_FullMethodName    = "/proto.ControlCenter/GetPingResults"
)

// ControlCenterClient is the client API for ControlCenter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ControlCenterClient interface {
	CreateCluster(ctx context.Context, in *Cluster, opts ...grpc.CallOption) (*Cluster, error)
	GetFleet(ctx context.Context, in *FleetQueryFilter, opts ...grpc.CallOption) (*Fleet, error)
	GetPoolStats(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*JobPoolStats, error)
	CreatePingJob(ctx context.Context, in *PingOptions, opts ...grpc.CallOption) (*ID, error)
	EvaluateJobs(ctx context.Context, in *TargetsEvaluationMessage, opts ...grpc.CallOption) (*TargetsEvaluationResult, error)
	GetJobs(ctx context.Context, in *JobsQueryFilter, opts ...grpc.CallOption) (*Jobs, error)
	GetJobSummaryByID(ctx context.Context, in *ID, opts ...grpc.CallOption) (*JobSummary, error)
	GetNewUUID(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*UUID, error)
	GetPingResults(ctx context.Context, in *PingResultsQueryFilter, opts ...grpc.CallOption) (*PingResults, error)
}

type controlCenterClient struct {
	cc grpc.ClientConnInterface
}

func NewControlCenterClient(cc grpc.ClientConnInterface) ControlCenterClient {
	return &controlCenterClient{cc}
}

func (c *controlCenterClient) CreateCluster(ctx context.Context, in *Cluster, opts ...grpc.CallOption) (*Cluster, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Cluster)
	err := c.cc.Invoke(ctx, ControlCenter_CreateCluster_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlCenterClient) GetFleet(ctx context.Context, in *FleetQueryFilter, opts ...grpc.CallOption) (*Fleet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Fleet)
	err := c.cc.Invoke(ctx, ControlCenter_GetFleet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlCenterClient) GetPoolStats(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*JobPoolStats, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JobPoolStats)
	err := c.cc.Invoke(ctx, ControlCenter_GetPoolStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlCenterClient) CreatePingJob(ctx context.Context, in *PingOptions, opts ...grpc.CallOption) (*ID, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ID)
	err := c.cc.Invoke(ctx, ControlCenter_CreatePingJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlCenterClient) EvaluateJobs(ctx context.Context, in *TargetsEvaluationMessage, opts ...grpc.CallOption) (*TargetsEvaluationResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TargetsEvaluationResult)
	err := c.cc.Invoke(ctx, ControlCenter_EvaluateJobs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlCenterClient) GetJobs(ctx context.Context, in *JobsQueryFilter, opts ...grpc.CallOption) (*Jobs, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Jobs)
	err := c.cc.Invoke(ctx, ControlCenter_GetJobs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlCenterClient) GetJobSummaryByID(ctx context.Context, in *ID, opts ...grpc.CallOption) (*JobSummary, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JobSummary)
	err := c.cc.Invoke(ctx, ControlCenter_GetJobSummaryByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlCenterClient) GetNewUUID(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*UUID, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UUID)
	err := c.cc.Invoke(ctx, ControlCenter_GetNewUUID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlCenterClient) GetPingResults(ctx context.Context, in *PingResultsQueryFilter, opts ...grpc.CallOption) (*PingResults, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResults)
	err := c.cc.Invoke(ctx, ControlCenter_GetPingResults_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControlCenterServer is the server API for ControlCenter service.
// All implementations must embed UnimplementedControlCenterServer
// for forward compatibility.
type ControlCenterServer interface {
	CreateCluster(context.Context, *Cluster) (*Cluster, error)
	GetFleet(context.Context, *FleetQueryFilter) (*Fleet, error)
	GetPoolStats(context.Context, *emptypb.Empty) (*JobPoolStats, error)
	CreatePingJob(context.Context, *PingOptions) (*ID, error)
	EvaluateJobs(context.Context, *TargetsEvaluationMessage) (*TargetsEvaluationResult, error)
	GetJobs(context.Context, *JobsQueryFilter) (*Jobs, error)
	GetJobSummaryByID(context.Context, *ID) (*JobSummary, error)
	GetNewUUID(context.Context, *emptypb.Empty) (*UUID, error)
	GetPingResults(context.Context, *PingResultsQueryFilter) (*PingResults, error)
	mustEmbedUnimplementedControlCenterServer()
}

// UnimplementedControlCenterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedControlCenterServer struct{}

func (UnimplementedControlCenterServer) CreateCluster(context.Context, *Cluster) (*Cluster, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCluster not implemented")
}
func (UnimplementedControlCenterServer) GetFleet(context.Context, *FleetQueryFilter) (*Fleet, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFleet not implemented")
}
func (UnimplementedControlCenterServer) GetPoolStats(context.Context, *emptypb.Empty) (*JobPoolStats, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPoolStats not implemented")
}
func (UnimplementedControlCenterServer) CreatePingJob(context.Context, *PingOptions) (*ID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePingJob not implemented")
}
func (UnimplementedControlCenterServer) EvaluateJobs(context.Context, *TargetsEvaluationMessage) (*TargetsEvaluationResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EvaluateJobs not implemented")
}
func (UnimplementedControlCenterServer) GetJobs(context.Context, *JobsQueryFilter) (*Jobs, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJobs not implemented")
}
func (UnimplementedControlCenterServer) GetJobSummaryByID(context.Context, *ID) (*JobSummary, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJobSummaryByID not implemented")
}
func (UnimplementedControlCenterServer) GetNewUUID(context.Context, *emptypb.Empty) (*UUID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNewUUID not implemented")
}
func (UnimplementedControlCenterServer) GetPingResults(context.Context, *PingResultsQueryFilter) (*PingResults, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPingResults not implemented")
}
func (UnimplementedControlCenterServer) mustEmbedUnimplementedControlCenterServer() {}
func (UnimplementedControlCenterServer) testEmbeddedByValue()                       {}

// UnsafeControlCenterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControlCenterServer will
// result in compilation errors.
type UnsafeControlCenterServer interface {
	mustEmbedUnimplementedControlCenterServer()
}

func RegisterControlCenterServer(s grpc.ServiceRegistrar, srv ControlCenterServer) {
	// If the following call pancis, it indicates UnimplementedControlCenterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ControlCenter_ServiceDesc, srv)
}

func _ControlCenter_CreateCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Cluster)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlCenterServer).CreateCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlCenter_CreateCluster_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlCenterServer).CreateCluster(ctx, req.(*Cluster))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlCenter_GetFleet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FleetQueryFilter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlCenterServer).GetFleet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlCenter_GetFleet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlCenterServer).GetFleet(ctx, req.(*FleetQueryFilter))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlCenter_GetPoolStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlCenterServer).GetPoolStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlCenter_GetPoolStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlCenterServer).GetPoolStats(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlCenter_CreatePingJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlCenterServer).CreatePingJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlCenter_CreatePingJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlCenterServer).CreatePingJob(ctx, req.(*PingOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlCenter_EvaluateJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TargetsEvaluationMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlCenterServer).EvaluateJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlCenter_EvaluateJobs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlCenterServer).EvaluateJobs(ctx, req.(*TargetsEvaluationMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlCenter_GetJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobsQueryFilter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlCenterServer).GetJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlCenter_GetJobs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlCenterServer).GetJobs(ctx, req.(*JobsQueryFilter))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlCenter_GetJobSummaryByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlCenterServer).GetJobSummaryByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlCenter_GetJobSummaryByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlCenterServer).GetJobSummaryByID(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlCenter_GetNewUUID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlCenterServer).GetNewUUID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlCenter_GetNewUUID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlCenterServer).GetNewUUID(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlCenter_GetPingResults_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingResultsQueryFilter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlCenterServer).GetPingResults(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlCenter_GetPingResults_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlCenterServer).GetPingResults(ctx, req.(*PingResultsQueryFilter))
	}
	return interceptor(ctx, in, info, handler)
}

// ControlCenter_ServiceDesc is the grpc.ServiceDesc for ControlCenter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ControlCenter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ControlCenter",
	HandlerType: (*ControlCenterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCluster",
			Handler:    _ControlCenter_CreateCluster_Handler,
		},
		{
			MethodName: "GetFleet",
			Handler:    _ControlCenter_GetFleet_Handler,
		},
		{
			MethodName: "GetPoolStats",
			Handler:    _ControlCenter_GetPoolStats_Handler,
		},
		{
			MethodName: "CreatePingJob",
			Handler:    _ControlCenter_CreatePingJob_Handler,
		},
		{
			MethodName: "EvaluateJobs",
			Handler:    _ControlCenter_EvaluateJobs_Handler,
		},
		{
			MethodName: "GetJobs",
			Handler:    _ControlCenter_GetJobs_Handler,
		},
		{
			MethodName: "GetJobSummaryByID",
			Handler:    _ControlCenter_GetJobSummaryByID_Handler,
		},
		{
			MethodName: "GetNewUUID",
			Handler:    _ControlCenter_GetNewUUID_Handler,
		},
		{
			MethodName: "GetPingResults",
			Handler:    _ControlCenter_GetPingResults_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cc.proto",
}
