// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.3
// source: nodes.proto

package services

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PingerBotClient is the client API for PingerBot service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PingerBotClient interface {
	StartScan(ctx context.Context, in *ScanOptions, opts ...grpc.CallOption) (*None, error)
}

type pingerBotClient struct {
	cc grpc.ClientConnInterface
}

func NewPingerBotClient(cc grpc.ClientConnInterface) PingerBotClient {
	return &pingerBotClient{cc}
}

func (c *pingerBotClient) StartScan(ctx context.Context, in *ScanOptions, opts ...grpc.CallOption) (*None, error) {
	out := new(None)
	err := c.cc.Invoke(ctx, "/proto.PingerBot/StartScan", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PingerBotServer is the server API for PingerBot service.
// All implementations must embed UnimplementedPingerBotServer
// for forward compatibility
type PingerBotServer interface {
	StartScan(context.Context, *ScanOptions) (*None, error)
	mustEmbedUnimplementedPingerBotServer()
}

// UnimplementedPingerBotServer must be embedded to have forward compatible implementations.
type UnimplementedPingerBotServer struct {
}

func (UnimplementedPingerBotServer) StartScan(context.Context, *ScanOptions) (*None, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartScan not implemented")
}
func (UnimplementedPingerBotServer) mustEmbedUnimplementedPingerBotServer() {}

// UnsafePingerBotServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PingerBotServer will
// result in compilation errors.
type UnsafePingerBotServer interface {
	mustEmbedUnimplementedPingerBotServer()
}

func RegisterPingerBotServer(s grpc.ServiceRegistrar, srv PingerBotServer) {
	s.RegisterService(&PingerBot_ServiceDesc, srv)
}

func _PingerBot_StartScan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScanOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PingerBotServer).StartScan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.PingerBot/StartScan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PingerBotServer).StartScan(ctx, req.(*ScanOptions))
	}
	return interceptor(ctx, in, info, handler)
}

// PingerBot_ServiceDesc is the grpc.ServiceDesc for PingerBot service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PingerBot_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.PingerBot",
	HandlerType: (*PingerBotServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartScan",
			Handler:    _PingerBot_StartScan_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nodes.proto",
}
