// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.3
// source: telegram.proto

package services

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TelegramAdminBotService_SendMessage_FullMethodName = "/proto.TelegramAdminBotService/SendMessage"
)

// TelegramAdminBotServiceClient is the client API for TelegramAdminBotService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TelegramAdminBotServiceClient interface {
	SendMessage(ctx context.Context, in *NewChatMessage, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type telegramAdminBotServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTelegramAdminBotServiceClient(cc grpc.ClientConnInterface) TelegramAdminBotServiceClient {
	return &telegramAdminBotServiceClient{cc}
}

func (c *telegramAdminBotServiceClient) SendMessage(ctx context.Context, in *NewChatMessage, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TelegramAdminBotService_SendMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TelegramAdminBotServiceServer is the server API for TelegramAdminBotService service.
// All implementations must embed UnimplementedTelegramAdminBotServiceServer
// for forward compatibility.
type TelegramAdminBotServiceServer interface {
	SendMessage(context.Context, *NewChatMessage) (*emptypb.Empty, error)
	mustEmbedUnimplementedTelegramAdminBotServiceServer()
}

// UnimplementedTelegramAdminBotServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTelegramAdminBotServiceServer struct{}

func (UnimplementedTelegramAdminBotServiceServer) SendMessage(context.Context, *NewChatMessage) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedTelegramAdminBotServiceServer) mustEmbedUnimplementedTelegramAdminBotServiceServer() {
}
func (UnimplementedTelegramAdminBotServiceServer) testEmbeddedByValue() {}

// UnsafeTelegramAdminBotServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TelegramAdminBotServiceServer will
// result in compilation errors.
type UnsafeTelegramAdminBotServiceServer interface {
	mustEmbedUnimplementedTelegramAdminBotServiceServer()
}

func RegisterTelegramAdminBotServiceServer(s grpc.ServiceRegistrar, srv TelegramAdminBotServiceServer) {
	// If the following call pancis, it indicates UnimplementedTelegramAdminBotServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TelegramAdminBotService_ServiceDesc, srv)
}

func _TelegramAdminBotService_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewChatMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelegramAdminBotServiceServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TelegramAdminBotService_SendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelegramAdminBotServiceServer).SendMessage(ctx, req.(*NewChatMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// TelegramAdminBotService_ServiceDesc is the grpc.ServiceDesc for TelegramAdminBotService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TelegramAdminBotService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.TelegramAdminBotService",
	HandlerType: (*TelegramAdminBotServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMessage",
			Handler:    _TelegramAdminBotService_SendMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "telegram.proto",
}
